name: ExtendableTime
version: 1.0
main: id.raznar.extendedtime.ExtendableTime
authors: [ Yusta ]
description: Extends world's time

commands:
  extendabletime:
    description: ExtendableTime main command
    usage: /<command>
    aliases: [extime]
    permission: extendabletime.admin